name: Push source to repo

on:
  workflow_dispatch:

jobs:
  push-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: clone source
        run: wget "source url here"

      - name: unzip
        run: unzip source.zip
       
      - name: Commit and push
        run: |
          git config --local user.name "abhiram79"
          git config --local user.email "email"
          git add .
          git commit -m "source updated"
          git push origin main

          
